In [1]:
import pandas as pd
file_path = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/eur_usd_10_years.csv"
filepath2 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/gbp_usd_10_years.csv"  
filepath3 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/usd_jpy_10_years.csv"
filepath4 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/usd_cny_10_years.csv"
filepath5 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/usd_cad_10_years.csv"

data = pd.read_csv(file_path, skiprows=1)
data2 = pd.read_csv(filepath2, skiprows=1)
data3 = pd.read_csv(filepath3, skiprows=1)
data4 = pd.read_csv(filepath4, skiprows=1)
data5 = pd.read_csv(filepath5, skiprows=1)

In [3]:
data.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
data2.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
data3.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
data4.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
data5.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

print(data.head())
print(data.columns)

         Date     Close      High       Low      Open  Volume
0        Date       NaN       NaN       NaN       NaN     NaN
1  2014-01-01  1.374495  1.377904  1.374400  1.374495     0.0
2  2014-01-02  1.376671  1.377467  1.363271  1.376595     0.0
3  2014-01-03  1.366662  1.367297  1.360170  1.366624     0.0
4  2014-01-06  1.359601  1.364610  1.357279  1.359582     0.0
Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [5]:
data = data[data['Date'] != 'Date']
data2 = data2[data2['Date'] != 'Date']
data3 = data3[data3['Date'] != 'Date']
data4 = data4[data4['Date'] != 'Date']
data5 = data5[data5['Date'] != 'Date']

In [6]:
data = data.drop(columns=['Volume'])
data2 = data2.drop(columns=['Volume'])
data3 = data3.drop(columns=['Volume'])
data4 = data4.drop(columns=['Volume'])
data5 = data5.drop(columns=['Volume'])

In [7]:
data.head()

         Date     Close      High       Low      Open
1  2014-01-01  1.374495  1.377904  1.374400  1.374495
2  2014-01-02  1.376671  1.377467  1.363271  1.376595
3  2014-01-03  1.366662  1.367297  1.360170  1.366624
4  2014-01-06  1.359601  1.364610  1.357279  1.359582
5  2014-01-07  1.363196  1.365799  1.359878  1.363066

In [9]:
data2.head()

         Date     Close      High       Low      Open
1  2014-01-01  1.656397  1.656397  1.656397  1.656397
2  2014-01-02  1.658072  1.660495  1.642387  1.657660
3  2014-01-03  1.644791  1.647501  1.640070  1.645007
4  2014-01-06  1.641309  1.643304  1.634254  1.641201
5  2014-01-07  1.641794  1.643548  1.637546  1.641497

In [7]:
cleaned_file_path = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/cleaned_eur_usd_10_years.csv"
cleaned_file_path_2 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/cleaned_gbp_usd_10_years.csv"
cleaned_file_path_3 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/cleaned_usd_jpy_10_years.csv"
cleaned_file_path_4 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/cleaned_usd_cny_10_years.csv"
cleaned_file_path_5 = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/cleaned_usd_cad_10_years.csv"
data.to_csv(cleaned_file_path, index=False)
data2.to_csv(cleaned_file_path_2, index=False)
data3.to_csv(cleaned_file_path_3, index=False)
data4.to_csv(cleaned_file_path_4, index=False)
data5.to_csv(cleaned_file_path_5, index=False)

: