In [8]:
import pandas as pd
file_path = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/eur_usd_10_years.csv"  
data = pd.read_csv(file_path, skiprows=1)

In [9]:
data.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

print(data.head())
print(data.columns)

         Date     Close      High       Low      Open  Volume
0        Date       NaN       NaN       NaN       NaN     NaN
1  2014-01-01  1.374495  1.377904  1.374400  1.374495     0.0
2  2014-01-02  1.376671  1.377467  1.363271  1.376595     0.0
3  2014-01-03  1.366662  1.367297  1.360170  1.366624     0.0
4  2014-01-06  1.359601  1.364610  1.357279  1.359582     0.0
Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [10]:
data = data[data['Date'] != 'Date']
data.head()

         Date     Close      High       Low      Open  Volume
1  2014-01-01  1.374495  1.377904  1.374400  1.374495     0.0
2  2014-01-02  1.376671  1.377467  1.363271  1.376595     0.0
3  2014-01-03  1.366662  1.367297  1.360170  1.366624     0.0
4  2014-01-06  1.359601  1.364610  1.357279  1.359582     0.0
5  2014-01-07  1.363196  1.365799  1.359878  1.363066     0.0

In [ ]:
data = data.drop(columns=['Volume'])

In [13]:
data.head()

         Date     Close      High       Low      Open
1  2014-01-01  1.374495  1.377904  1.374400  1.374495
2  2014-01-02  1.376671  1.377467  1.363271  1.376595
3  2014-01-03  1.366662  1.367297  1.360170  1.366624
4  2014-01-06  1.359601  1.364610  1.357279  1.359582
5  2014-01-07  1.363196  1.365799  1.359878  1.363066

In [14]:
data = data.reset_index(drop=True)
data.head()

         Date     Close      High       Low      Open
0  2014-01-01  1.374495  1.377904  1.374400  1.374495
1  2014-01-02  1.376671  1.377467  1.363271  1.376595
2  2014-01-03  1.366662  1.367297  1.360170  1.366624
3  2014-01-06  1.359601  1.364610  1.357279  1.359582
4  2014-01-07  1.363196  1.365799  1.359878  1.363066

In [ ]:
cleaned_file_path = "C:/Users/vamsh/OneDrive/Desktop/Forex trading/Forex-Trading/config/forexrate/forex data/cleaned_eur_usd_10_years.csv"
data.to_csv(cleaned_file_path, index=False)